migrating msys2-runtime to cygwin
msys2-runtime commit-id for cygwin1.dll is from:
https://github.com/lygstate/msys2-runtime/commit/fd5ce305d44723feb3e60c927295d5973ee7692b

The commit-id for msys-2.0.dll and cygwin1.dll should not be the same.
So that they can call each other properly

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

diff --git a/msys2-runtime/PKGBUILD b/msys2-runtime/PKGBUILD
--- a/msys2-runtime/PKGBUILD
+++ b/msys2-runtime/PKGBUILD
@@ -29,6 +29,31 @@ makedepends=('cocom'
 # re zipman: https://github.com/msys2/MSYS2-packages/pull/2687#issuecomment-965714874
 options=('!zipman')
 
+currnent_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
+source "${currnent_script_dir}/../msys2-runtime/check-bootstrap.sh"
+# _build_as_msys_2_dll==false means build msys2-runtime as cygwin1.dll
+_build_as_msys_2_dll=true
+if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin" ]]; then
+  pkgrel=$pkgrel
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin_hook" ]]; then
+  pkgrel=5
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage0" ]]; then
+  pkgrel=6
+  _build_as_msys_2_dll=false
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage1" ]]; then
+  pkgrel=7
+  _build_as_msys_2_dll=false
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage2" ]]; then
+  pkgrel=8
+  _build_as_msys_2_dll=false
+elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage3" ]]; then
+  pkgrel=9
+  _build_as_msys_2_dll=false
+else
+ echo "Invalid MSYS_BOOTSTRAP_STAGE: '$MSYS_BOOTSTRAP_STAGE'" >&2
+ exit -1
+fi
+
 _patches=(
   # patches from https://github.com/msys2/msys2-runtime
   0001-Fix-msys-library-name-in-import-libraries.patch
@@ -70,6 +95,39 @@ _patches=(
   0037-uname-report-msys2-runtime-commit-hash-too.patch
   0038-Cygwin-Adjust-CWD-magic-to-accommodate-for-the-lates.patch
   0039-Cygwin-Fix-segfault-when-XSAVE-area-sizes-are-unalig.patch
+  0040-Revert-strace.cc-Don-t-set-MSYS-noglob.patch
+  0041-Revert-Rename-dll-from-cygwin-to-msys.patch
+  0042-Revert-uname-allow-setting-the-system-name-to-CYGWIN.patch
+  0043-Revert-Add-functionality-for-changing-OS-name-via-MS.patch
+  0044-Add-functionality-for-changing-OS-name-via-MSYSTEM-e.patch
+  0045-Add-support-for-MSYS-environment-variable-instead-of.patch
+  0046-strace.cc-Don-t-set-CYGWIN-noglob.patch
+  0047-Convert-to-use-msys-style-named-pipe.patch
+  0048-Rename-dll-from-cygwin-to-msys.patch
+  0049-Revert-Add-support-for-MSYS-environment-variable-ins.patch
+  0050-Support-for-both-MSYS-and-CYGWIN-environment-variabl.patch
+  0051-Revert-hookapi.cc-of-Rename-dll-from-cygwin-to-msys.patch
+  0052-hookapi.c-Support-for-both-cygwin-and-msys2-for-boot.patch
+)
+
+# The original msys2-runtime patches that built as msys-2.0.dll
+_patches_exclude_stage_origin=(
+  0049-Revert-Add-support-for-MSYS-environment-variable-ins.patch
+  0050-Support-for-both-MSYS-and-CYGWIN-environment-variabl.patch
+  0051-Revert-hookapi.cc-of-Rename-dll-from-cygwin-to-msys.patch
+  0052-hookapi.c-Support-for-both-cygwin-and-msys2-for-boot.patch
+)
+
+# The original msys2-runtime patches with hookapi and `Support-for-both-MSYS-and-CYGWIN-environment-variable` patches that built as msys-2.0.dll
+# All patches are included.
+_patches_exclude_stage_origin_hook=(
+)
+
+# The new msys2-runtime that built as cygwin1.dll
+_patches_exclude_for_cygwin_dll=(
+  0001-Fix-msys-library-name-in-import-libraries.patch
+  0048-Rename-dll-from-cygwin-to-msys.patch
+  0051-Revert-hookapi.cc-of-Rename-dll-from-cygwin-to-msys.patch
 )
 
 source=(
@@ -77,6 +135,8 @@ source=(
 
   ${_patches[@]}
 
+  # The commit-id for msys-2.0.dll and cygwin1.dll should not be the same.
+  msys2-runtime-cygwin1.commit
   msys2-runtime.commit
 )
 
@@ -120,6 +180,20 @@ sha256sums=('ce144fea2ed9896fc950e811a52ea384d55bad7804b703c1a483b53ae8def0c6'
             '524f0c9922d8ac8398ef6ee8050afee157c8c93b24d4056826db36e406861ab2'
             '15541ccdf894510421b22a6bc901d1fb8da278a4101435b4a7b1ec2a211f84e2'
             '8244f4bb7890db0e87ec9aa21ff58989ca7cf6162f27ea782d72e3d0039545d9'
+            'b5b9f6ea461d4b2155568ce4d99d804e37e8b008c6156ef1a5279ed04d4d05ed'
+            'ac6a1508b514d110cf12713067557844c5804df995a29915b71027493186f12f'
+            '77b19346c52395f623e956d860e275d6a2bb08f56d17565ba104cd9caf9cb335'
+            '8c6f1ab635f1e8ee861d811e7b017bfa5ceb7e1088103e144b2f91d2805b1d29'
+            '635c839262bfbad7b6f0286a00c425e3f620e188f400a09a5968e8a52ff54c4b'
+            '9777e7681ad31b640e93e50e9bd53127af071c1aac5f3069af150a925ae0b261'
+            '8ab623a9fb4db03868525cc2106916444bada4d3dd576cadf4ce9d61f414f4d7'
+            '0522257ed6d6a4712e20bad629416f0e46a32bda1619e9c668dcbd77d91ec992'
+            'a6fdbe07864baef1540b7c8d3a5693c7d0469d4b2bf8bb91afe78e3b39e1be29'
+            'a3a0200faf9fd7e63f0193fdac3595ead517c18cd3026356eae47bc1acedbdbc'
+            'bef9bd130a79c4cbc6fd28d008fbfca8231a5e223fab6c1f469a34266b548d19'
+            'f1e702df314750b79c7694e4a6e7df9aeea196adfb1239eb99a68cc669debe4e'
+            '6b6c6bd4e72bcc674b257ed64c9c2996d30ad92a56234a295eb27de695ab3571'
+            '7104fc6c2653842a1769de2cab072592bed7c71d45bf666d5ac1609b2bf66c0b'
             'f62650edff96d34beac4a1d10a38807b86d679560aee58ac758a15b2d86059a6')
 
 # Helper macros to help make tasks easier #
@@ -149,6 +223,25 @@ del_file_exists() {
 }
 # =========================================== #
 
+# Function: exclude_list (list_to_filter, items_to_exclude)
+exclude_list() {
+  local -n arr=$1      # Reference to the main array
+  local -n exclude=$2  # Reference to the exclusion array
+  local -A ex_map      # Associative array for O(1) lookup
+  local result=()
+
+  # Build lookup map from the exclusion list
+  for item in "${exclude[@]}"; do ex_map["$item"]=1; done
+
+  # Filter the main array
+  for item in "${arr[@]}"; do
+      [[ -z "${ex_map[$item]}" ]] && result+=("$item")
+  done
+
+  # Output filtered list (or re-assign to original array if desired)
+  echo "${result[@]}"
+}
+
 prepare() {
   cd "${srcdir}"/msys2-runtime
   if test true != "$(git config core.symlinks)"
@@ -158,6 +251,17 @@ prepare() {
   fi
   del_file_exists winsup/cygwin/msys2_path_conv.cc \
     winsup/cygwin/msys2_path_conv.h
+
+  if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin" ]]; then
+      _patches=($(exclude_list _patches _patches_exclude_stage_origin))
+  elif [[ "$MSYS_BOOTSTRAP_STAGE" == "stage_origin_hook" ]]; then
+      _patches=($(exclude_list _patches _patches_exclude_stage_origin_hook))
+  elif [[ "$_build_as_msys_2_dll" == "false" ]]; then
+      _patches=($(exclude_list _patches _patches_exclude_for_cygwin_dll))
+  else
+    echo "Invalid MSYS_BOOTSTRAP_STAGE: '$MSYS_BOOTSTRAP_STAGE'" >&2
+    exit -1
+  fi
 
   for patch_filename in "${_patches[@]}"; do
     apply_git_am_with_msg ${patch_filename}
@@ -186,22 +290,60 @@ build() {
 
   (cd "${srcdir}/msys2-runtime/winsup" && ./autogen.sh)
 
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    msys2_runtime_commit_id=$(cat "${srcdir}/msys2-runtime.commit")
+  else
+    msys2_runtime_commit_id=$(cat "${srcdir}/msys2-runtime-cygwin1.commit")
+  fi
+
   "${srcdir}"/msys2-runtime/configure \
-    --with-msys2-runtime-commit="$(cat "${srcdir}/msys2-runtime.commit")" \
+    --with-msys2-runtime-commit="$msys2_runtime_commit_id" \
     --prefix=/usr \
     --build=${CHOST} \
     --sysconfdir=/etc \
     "${extra_config[@]}"
   LC_ALL=C make
+
+  if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage0" ]]; then
+    cp -af /usr/lib/libmsys-2.0.a /usr/lib/libmsys-2.0.a.origin
+    cp -af /usr/lib/libcygwin.a /usr/lib/libcygwin.a.origin
+    cp -af /usr/lib/libg.a /usr/lib/libg.a.origin
+    cp -af /usr/lib/crt0.o /usr/lib/crt0.o.origin
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/libcygwin.a /usr/lib/libmsys-2.0.a
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/libcygwin.a /usr/lib/libcygwin.a
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/libcygwin.a /usr/lib/libg.a
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/crt0.o /usr/lib/crt0.o
+    cp -f ./x86_64-pc-cygwin/winsup/cygwin/gcrt0.o /usr/lib/gcrt0.o
+    find | grep \\.exe$ | xargs -I ARG rm -f ARG
+
+    LC_ALL=C make
+  fi
+
   LC_ALL=C make -j1 DESTDIR="${srcdir}"/dest install
+
+  if [[ "$MSYS_BOOTSTRAP_STAGE" == "stage0" ]]; then
+    cp -af /usr/lib/libmsys-2.0.a.origin /usr/lib/libmsys-2.0.a
+    cp -af /usr/lib/libcygwin.a.origin /usr/lib/libcygwin.a
+    cp -af /usr/lib/libg.a.origin /usr/lib/libg.a
+    cp -af /usr/lib/crt0.o.origin /usr/lib/crt0.o
+    rm /usr/lib/*.origin
+  fi
 
   rm -rf "${srcdir}"/dest/etc
 
-  # split debug info from msys-2.0.dll
-  cd "${srcdir}"/dest
-  objcopy --add-gnu-debuglink=/dev/null --only-keep-debug usr/bin/msys-2.0.dll usr/bin/msys-2.0.dbg
-  objcopy -g --add-gnu-debuglink=usr/bin/msys-2.0.dbg usr/bin/msys-2.0.dll usr/bin/msys-2.0.dll.new
-  mv -f usr/bin/msys-2.0.dll.new usr/bin/msys-2.0.dll
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    # split debug info from msys-2.0.dll
+    cd "${srcdir}"/dest
+    objcopy --add-gnu-debuglink=/dev/null --only-keep-debug usr/bin/msys-2.0.dll usr/bin/msys-2.0.dbg
+    objcopy -g --add-gnu-debuglink=usr/bin/msys-2.0.dbg usr/bin/msys-2.0.dll usr/bin/msys-2.0.dll.new
+    mv -f usr/bin/msys-2.0.dll.new usr/bin/msys-2.0.dll
+  else
+    # split debug info from cygwin1.dll
+    cd "${srcdir}"/dest
+    objcopy --add-gnu-debuglink=/dev/null --only-keep-debug usr/bin/cygwin1.dll usr/bin/cygwin1.dbg
+    objcopy -g --add-gnu-debuglink=usr/bin/cygwin1.dbg usr/bin/cygwin1.dll usr/bin/cygwin1.dll.new
+    mv -f usr/bin/cygwin1.dll.new usr/bin/cygwin1.dll
+  fi
 }
 
 package_msys2-runtime() {
@@ -212,7 +354,11 @@ package_msys2-runtime() {
   mkdir -p "${pkgdir}"/usr
   cp -rf "${srcdir}"/dest/usr/bin "${pkgdir}"/usr/
   cp -rf "${srcdir}"/dest/usr/libexec "${pkgdir}"/usr/
-  rm -f "${pkgdir}"/usr/bin/msys-2.0.dbg
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    rm -f "${pkgdir}"/usr/bin/msys-2.0.dbg
+  else
+    rm -f "${pkgdir}"/usr/bin/cygwin1.dbg
+  fi
   rm -f "${pkgdir}"/usr/bin/cyglsa-config
   rm -f "${pkgdir}"/usr/bin/cyglsa.dll
   rm -f "${pkgdir}"/usr/bin/cyglsa64.dll
@@ -229,7 +375,11 @@ package_msys2-runtime-devel() {
   options=('!strip')
 
   mkdir -p "${pkgdir}"/usr/bin
-  cp -f "${srcdir}"/dest/usr/bin/msys-2.0.dbg "${pkgdir}"/usr/bin/
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    cp -f "${srcdir}"/dest/usr/bin/msys-2.0.dbg "${pkgdir}"/usr/bin/
+  else
+    cp -f "${srcdir}"/dest/usr/bin/cygwin1.dbg "${pkgdir}"/usr/bin/
+  fi
   cp -rLf "${srcdir}"/dest/usr/${CHOST}/include "${pkgdir}"/usr/
   rm -f "${pkgdir}"/usr/include/iconv.h
   rm -f "${pkgdir}"/usr/include/unctrl.h
@@ -238,6 +388,11 @@ package_msys2-runtime-devel() {
 
   cp -rLf "${srcdir}"/dest/usr/${CHOST}/lib "${pkgdir}"/usr/
 
-  # compatibility with Cygwin toolchains
-  cp "${srcdir}"/dest/usr/${CHOST}/lib/libmsys-2.0.a "${pkgdir}"/usr/lib/libcygwin.a
+  if [[ "$_build_as_msys_2_dll" == "true" ]]; then
+    # compatibility with Cygwin toolchains
+    cp "${srcdir}"/dest/usr/${CHOST}/lib/libmsys-2.0.a "${pkgdir}"/usr/lib/libcygwin.a
+  else
+    # compatibility with Msys2 toolchains for bootstrap
+    cp "${srcdir}"/dest/usr/${CHOST}/lib/libcygwin.a "${pkgdir}"/usr/lib/libmsys-2.0.a
+  fi
 }
